[phases.setup]
nixPkgs = ["php", "phpExtensions.curl", "phpExtensions.json", "phpExtensions.session"]

[phases.install]
cmds = ["echo 'No installation needed'"]

[start]
cmd = "php -S 0.0.0.0:${PORT} -t ."
